//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalNetwork.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class digimarketEntities1 : DbContext
    {
        public digimarketEntities1()
            : base("name=digimarketEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Article> Articles { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<Rate> Rates { get; set; }
        public virtual DbSet<Rates_History> Rates_History { get; set; }
        public virtual DbSet<Site> Sites { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<User_Articles> User_Articles { get; set; }
        public virtual DbSet<User_Marketing_Source> User_Marketing_Source { get; set; }
    
        public virtual int add_article(Nullable<int> aid, string article_url, Nullable<bool> status, string title, string summary, string photo_url, Nullable<System.DateTime> modified_date, string site_url, string category, string sub_category, Nullable<bool> custom)
        {
            var aidParameter = aid.HasValue ?
                new ObjectParameter("aid", aid) :
                new ObjectParameter("aid", typeof(int));
    
            var article_urlParameter = article_url != null ?
                new ObjectParameter("article_url", article_url) :
                new ObjectParameter("article_url", typeof(string));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(bool));
    
            var titleParameter = title != null ?
                new ObjectParameter("title", title) :
                new ObjectParameter("title", typeof(string));
    
            var summaryParameter = summary != null ?
                new ObjectParameter("summary", summary) :
                new ObjectParameter("summary", typeof(string));
    
            var photo_urlParameter = photo_url != null ?
                new ObjectParameter("photo_url", photo_url) :
                new ObjectParameter("photo_url", typeof(string));
    
            var modified_dateParameter = modified_date.HasValue ?
                new ObjectParameter("modified_date", modified_date) :
                new ObjectParameter("modified_date", typeof(System.DateTime));
    
            var site_urlParameter = site_url != null ?
                new ObjectParameter("site_url", site_url) :
                new ObjectParameter("site_url", typeof(string));
    
            var categoryParameter = category != null ?
                new ObjectParameter("category", category) :
                new ObjectParameter("category", typeof(string));
    
            var sub_categoryParameter = sub_category != null ?
                new ObjectParameter("sub_category", sub_category) :
                new ObjectParameter("sub_category", typeof(string));
    
            var customParameter = custom.HasValue ?
                new ObjectParameter("custom", custom) :
                new ObjectParameter("custom", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("add_article", aidParameter, article_urlParameter, statusParameter, titleParameter, summaryParameter, photo_urlParameter, modified_dateParameter, site_urlParameter, categoryParameter, sub_categoryParameter, customParameter);
        }
    
        public virtual int add_payment(string uid, Nullable<int> traffic, Nullable<decimal> amount, Nullable<System.DateTime> from_date, Nullable<System.DateTime> to_date, Nullable<System.DateTime> pay_date)
        {
            var uidParameter = uid != null ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(string));
    
            var trafficParameter = traffic.HasValue ?
                new ObjectParameter("traffic", traffic) :
                new ObjectParameter("traffic", typeof(int));
    
            var amountParameter = amount.HasValue ?
                new ObjectParameter("amount", amount) :
                new ObjectParameter("amount", typeof(decimal));
    
            var from_dateParameter = from_date.HasValue ?
                new ObjectParameter("from_date", from_date) :
                new ObjectParameter("from_date", typeof(System.DateTime));
    
            var to_dateParameter = to_date.HasValue ?
                new ObjectParameter("to_date", to_date) :
                new ObjectParameter("to_date", typeof(System.DateTime));
    
            var pay_dateParameter = pay_date.HasValue ?
                new ObjectParameter("pay_date", pay_date) :
                new ObjectParameter("pay_date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("add_payment", uidParameter, trafficParameter, amountParameter, from_dateParameter, to_dateParameter, pay_dateParameter);
        }
    
        public virtual int add_shared_article(string uid, Nullable<int> serial_no, Nullable<bool> copied, Nullable<bool> shared)
        {
            var uidParameter = uid != null ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(string));
    
            var serial_noParameter = serial_no.HasValue ?
                new ObjectParameter("serial_no", serial_no) :
                new ObjectParameter("serial_no", typeof(int));
    
            var copiedParameter = copied.HasValue ?
                new ObjectParameter("copied", copied) :
                new ObjectParameter("copied", typeof(bool));
    
            var sharedParameter = shared.HasValue ?
                new ObjectParameter("shared", shared) :
                new ObjectParameter("shared", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("add_shared_article", uidParameter, serial_noParameter, copiedParameter, sharedParameter);
        }
    
        public virtual int add_site(string site, string site_name, string gid, string email)
        {
            var siteParameter = site != null ?
                new ObjectParameter("site", site) :
                new ObjectParameter("site", typeof(string));
    
            var site_nameParameter = site_name != null ?
                new ObjectParameter("site_name", site_name) :
                new ObjectParameter("site_name", typeof(string));
    
            var gidParameter = gid != null ?
                new ObjectParameter("gid", gid) :
                new ObjectParameter("gid", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("add_site", siteParameter, site_nameParameter, gidParameter, emailParameter);
        }
    
        public virtual int add_ums(Nullable<int> ums_id, string token, string uid)
        {
            var ums_idParameter = ums_id.HasValue ?
                new ObjectParameter("ums_id", ums_id) :
                new ObjectParameter("ums_id", typeof(int));
    
            var tokenParameter = token != null ?
                new ObjectParameter("token", token) :
                new ObjectParameter("token", typeof(string));
    
            var uidParameter = uid != null ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("add_ums", ums_idParameter, tokenParameter, uidParameter);
        }
    
        public virtual ObjectResult<admin_sign_in_Result> admin_sign_in(string email)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<admin_sign_in_Result>("admin_sign_in", emailParameter);
        }
    
        public virtual int admin_sign_up(string email, string name, string photo)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var photoParameter = photo != null ?
                new ObjectParameter("photo", photo) :
                new ObjectParameter("photo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("admin_sign_up", emailParameter, nameParameter, photoParameter);
        }
    
        public virtual int admin_update(string email, string name, string photo)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var photoParameter = photo != null ?
                new ObjectParameter("photo", photo) :
                new ObjectParameter("photo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("admin_update", emailParameter, nameParameter, photoParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> count_ums(string uid)
        {
            var uidParameter = uid != null ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("count_ums", uidParameter);
        }
    
        public virtual int delete_article(Nullable<int> serial)
        {
            var serialParameter = serial.HasValue ?
                new ObjectParameter("serial", serial) :
                new ObjectParameter("serial", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delete_article", serialParameter);
        }
    
        public virtual int delete_site(string site_url, string email)
        {
            var site_urlParameter = site_url != null ?
                new ObjectParameter("site_url", site_url) :
                new ObjectParameter("site_url", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delete_site", site_urlParameter, emailParameter);
        }
    
        public virtual int delete_ums(Nullable<int> ums_id)
        {
            var ums_idParameter = ums_id.HasValue ?
                new ObjectParameter("ums_id", ums_id) :
                new ObjectParameter("ums_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delete_ums", ums_idParameter);
        }
    
        public virtual ObjectResult<get_admin_articles_Result> get_admin_articles(string email, string site)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var siteParameter = site != null ?
                new ObjectParameter("site", site) :
                new ObjectParameter("site", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_admin_articles_Result>("get_admin_articles", emailParameter, siteParameter);
        }
    
        public virtual ObjectResult<get_admin_gid_Result> get_admin_gid(string site)
        {
            var siteParameter = site != null ?
                new ObjectParameter("site", site) :
                new ObjectParameter("site", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_admin_gid_Result>("get_admin_gid", siteParameter);
        }
    
        public virtual ObjectResult<get_admin_single_article_Result> get_admin_single_article(Nullable<int> aid, string email, string site)
        {
            var aidParameter = aid.HasValue ?
                new ObjectParameter("aid", aid) :
                new ObjectParameter("aid", typeof(int));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var siteParameter = site != null ?
                new ObjectParameter("site", site) :
                new ObjectParameter("site", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_admin_single_article_Result>("get_admin_single_article", aidParameter, emailParameter, siteParameter);
        }
    
        public virtual ObjectResult<get_all_articles_Result> get_all_articles(string site)
        {
            var siteParameter = site != null ?
                new ObjectParameter("site", site) :
                new ObjectParameter("site", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_all_articles_Result>("get_all_articles", siteParameter);
        }
    
        public virtual ObjectResult<string> get_all_site()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("get_all_site");
        }
    
        public virtual ObjectResult<get_articles_Result> get_articles(string uid, string cat, string subcat)
        {
            var uidParameter = uid != null ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(string));
    
            var catParameter = cat != null ?
                new ObjectParameter("cat", cat) :
                new ObjectParameter("cat", typeof(string));
    
            var subcatParameter = subcat != null ?
                new ObjectParameter("subcat", subcat) :
                new ObjectParameter("subcat", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_articles_Result>("get_articles", uidParameter, catParameter, subcatParameter);
        }
    
        public virtual ObjectResult<get_payment_Result> get_payment(string uid, Nullable<int> traffic, Nullable<decimal> amount, Nullable<System.DateTime> from_date, Nullable<System.DateTime> to_date, Nullable<System.DateTime> pay_date)
        {
            var uidParameter = uid != null ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(string));
    
            var trafficParameter = traffic.HasValue ?
                new ObjectParameter("traffic", traffic) :
                new ObjectParameter("traffic", typeof(int));
    
            var amountParameter = amount.HasValue ?
                new ObjectParameter("amount", amount) :
                new ObjectParameter("amount", typeof(decimal));
    
            var from_dateParameter = from_date.HasValue ?
                new ObjectParameter("from_date", from_date) :
                new ObjectParameter("from_date", typeof(System.DateTime));
    
            var to_dateParameter = to_date.HasValue ?
                new ObjectParameter("to_date", to_date) :
                new ObjectParameter("to_date", typeof(System.DateTime));
    
            var pay_dateParameter = pay_date.HasValue ?
                new ObjectParameter("pay_date", pay_date) :
                new ObjectParameter("pay_date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_payment_Result>("get_payment", uidParameter, trafficParameter, amountParameter, from_dateParameter, to_dateParameter, pay_dateParameter);
        }
    
        public virtual ObjectResult<get_rate_Result> get_rate(string category)
        {
            var categoryParameter = category != null ?
                new ObjectParameter("category", category) :
                new ObjectParameter("category", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_rate_Result>("get_rate", categoryParameter);
        }
    
        public virtual ObjectResult<get_shared_article_Result> get_shared_article(string uid, string cat, string subcat)
        {
            var uidParameter = uid != null ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(string));
    
            var catParameter = cat != null ?
                new ObjectParameter("cat", cat) :
                new ObjectParameter("cat", typeof(string));
    
            var subcatParameter = subcat != null ?
                new ObjectParameter("subcat", subcat) :
                new ObjectParameter("subcat", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_shared_article_Result>("get_shared_article", uidParameter, catParameter, subcatParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> get_shared_article_serial(Nullable<int> serial)
        {
            var serialParameter = serial.HasValue ?
                new ObjectParameter("serial", serial) :
                new ObjectParameter("serial", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("get_shared_article_serial", serialParameter);
        }
    
        public virtual ObjectResult<get_site_Result> get_site(string email)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_site_Result>("get_site", emailParameter);
        }
    
        public virtual ObjectResult<get_ums_Result> get_ums(string uid)
        {
            var uidParameter = uid != null ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_ums_Result>("get_ums", uidParameter);
        }
    
        public virtual ObjectResult<get_user_single_article_Result> get_user_single_article(Nullable<int> serial)
        {
            var serialParameter = serial.HasValue ?
                new ObjectParameter("serial", serial) :
                new ObjectParameter("serial", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_user_single_article_Result>("get_user_single_article", serialParameter);
        }
    
        public virtual ObjectResult<getArticleBySerial_Result> getArticleBySerial(Nullable<int> serial)
        {
            var serialParameter = serial.HasValue ?
                new ObjectParameter("serial", serial) :
                new ObjectParameter("serial", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getArticleBySerial_Result>("getArticleBySerial", serialParameter);
        }
    
        public virtual int update_article_data(Nullable<int> serial_no, string article_url, string title, string summary, string photo_url, Nullable<System.DateTime> modified_date)
        {
            var serial_noParameter = serial_no.HasValue ?
                new ObjectParameter("serial_no", serial_no) :
                new ObjectParameter("serial_no", typeof(int));
    
            var article_urlParameter = article_url != null ?
                new ObjectParameter("article_url", article_url) :
                new ObjectParameter("article_url", typeof(string));
    
            var titleParameter = title != null ?
                new ObjectParameter("title", title) :
                new ObjectParameter("title", typeof(string));
    
            var summaryParameter = summary != null ?
                new ObjectParameter("summary", summary) :
                new ObjectParameter("summary", typeof(string));
    
            var photo_urlParameter = photo_url != null ?
                new ObjectParameter("photo_url", photo_url) :
                new ObjectParameter("photo_url", typeof(string));
    
            var modified_dateParameter = modified_date.HasValue ?
                new ObjectParameter("modified_date", modified_date) :
                new ObjectParameter("modified_date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("update_article_data", serial_noParameter, article_urlParameter, titleParameter, summaryParameter, photo_urlParameter, modified_dateParameter);
        }
    
        public virtual int update_articles(Nullable<bool> status, Nullable<int> serial)
        {
            var statusParameter = status.HasValue ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(bool));
    
            var serialParameter = serial.HasValue ?
                new ObjectParameter("serial", serial) :
                new ObjectParameter("serial", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("update_articles", statusParameter, serialParameter);
        }
    
        public virtual int update_rates(string category, Nullable<decimal> rate, Nullable<System.DateTime> date)
        {
            var categoryParameter = category != null ?
                new ObjectParameter("category", category) :
                new ObjectParameter("category", typeof(string));
    
            var rateParameter = rate.HasValue ?
                new ObjectParameter("rate", rate) :
                new ObjectParameter("rate", typeof(decimal));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("date", date) :
                new ObjectParameter("date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("update_rates", categoryParameter, rateParameter, dateParameter);
        }
    
        public virtual int update_shared_articles(string uid, Nullable<int> serial, Nullable<bool> shared, Nullable<bool> copied)
        {
            var uidParameter = uid != null ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(string));
    
            var serialParameter = serial.HasValue ?
                new ObjectParameter("serial", serial) :
                new ObjectParameter("serial", typeof(int));
    
            var sharedParameter = shared.HasValue ?
                new ObjectParameter("shared", shared) :
                new ObjectParameter("shared", typeof(bool));
    
            var copiedParameter = copied.HasValue ?
                new ObjectParameter("copied", copied) :
                new ObjectParameter("copied", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("update_shared_articles", uidParameter, serialParameter, sharedParameter, copiedParameter);
        }
    
        public virtual int update_site(string site_name, string site)
        {
            var site_nameParameter = site_name != null ?
                new ObjectParameter("site_name", site_name) :
                new ObjectParameter("site_name", typeof(string));
    
            var siteParameter = site != null ?
                new ObjectParameter("site", site) :
                new ObjectParameter("site", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("update_site", site_nameParameter, siteParameter);
        }
    
        public virtual ObjectResult<user_sign_in_Result> user_sign_in(string uid)
        {
            var uidParameter = uid != null ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<user_sign_in_Result>("user_sign_in", uidParameter);
        }
    
        public virtual int user_sign_up(string uid, string name, string photo, string fullname)
        {
            var uidParameter = uid != null ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var photoParameter = photo != null ?
                new ObjectParameter("photo", photo) :
                new ObjectParameter("photo", typeof(string));
    
            var fullnameParameter = fullname != null ?
                new ObjectParameter("fullname", fullname) :
                new ObjectParameter("fullname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("user_sign_up", uidParameter, nameParameter, photoParameter, fullnameParameter);
        }
    
        public virtual int user_update(string uid, string photo)
        {
            var uidParameter = uid != null ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(string));
    
            var photoParameter = photo != null ?
                new ObjectParameter("photo", photo) :
                new ObjectParameter("photo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("user_update", uidParameter, photoParameter);
        }
    
        public virtual ObjectResult<get_user_traffic_Result> get_user_traffic(string uid)
        {
            var uidParameter = uid != null ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_user_traffic_Result>("get_user_traffic", uidParameter);
        }
    }
}
