//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalNetwork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int n_id { get; set; }
        public string message { get; set; }
        public string category { get; set; }
        public string uid { get; set; }
        public bool status { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual User User { get; set; }
    }
}
