//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalNetwork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Articles
    {
        public string uid { get; set; }
        public int serial_no { get; set; }
        public bool copied { get; set; }
        public bool shared { get; set; }
    
        public virtual Article Article { get; set; }
        public virtual User User { get; set; }
    }
}
